name: 'action-tag-issue-with-branch'
description: 'Label issues if there is a branch referencing it.'
branding:
  icon: 'move'  
  color: 'purple'
inputs:
  action-token:
    description: 'Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
